"use client";
import "./globals.css";
import { Plus_Jakarta_Sans } from "next/font/google";
import { AuthContextProvider } from "@/components/contexts/Auth";
import { useEffect, useContext } from "react";
import { AuthContext } from "@/components/contexts/Auth";
import LocalStorage from "@/lib/integration/localstorage";
import jwt_decode from "jwt-decode";
const jakarta_sans = Plus_Jakarta_Sans({ subsets: ["latin"] });
// export const metadata = {
//   title: "Storynoi | landing page",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  // const { state, dispatch } = useContext(AuthContext);
  // const storage = new LocalStorage();
  // useEffect(() => {
  //   // Check for token
  //   if (storage.get("jwtToken")) {
  //     // Set auth token header auth
  //     // setAuthToken(localStorage.jwtToken);
  //     // Decode token and get user info and exp
  //     const decoded = jwt_decode(storage.get("jwtToken"));
  //     // Set user and isAuthenticated
  //     dispatch({ type: "SET_CURRENT_USER", payload: decoded });

  //     // Check for expired token
  //     const currentTime = Date.now() / 1000;
  //     if (decoded.exp < currentTime) {
  //       dispatch({ type: "LOGOUT" });
  //     }
  //   }
  // }, []);

  return (
    <html lang="en">
      <body className={jakarta_sans.className}>
        {/* <GoogleOAuthProvider clientId="369545017372-7a86qfketnub5jltj008k1k8suseo3ut.apps.googleusercontent.com"> */}{" "}
        <AuthContextProvider>{children}</AuthContextProvider>
        {/* </GoogleOAuthProvider> */}
      </body>
    </html>
  );
}
