"use client";
import "./globals.css";
import { Plus_Jakarta_Sans } from "next/font/google";
import { AuthContextProvider } from "@/components/contexts/Auth";
import { GoogleOAuthProvider } from "@react-oauth/google";
const jakarta_sans = Plus_Jakarta_Sans({ subsets: ["latin"] });
// export const metadata = {
//   title: "Storynoi | landing page",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jakarta_sans.className}>
        <GoogleOAuthProvider clientId="369545017372-7a86qfketnub5jltj008k1k8suseo3ut.apps.googleusercontent.com">
          {" "}
          <AuthContextProvider>{children}</AuthContextProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
